#ifndef SYSTEMUICELLULARTOGGLE_GLOBAL_H
#define SYSTEMUICELLULARTOGGLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYSTEMUICELLULARTOGGLE_LIBRARY)
#  define SYSTEMUICELLULARTOGGLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYSTEMUICELLULARTOGGLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYSTEMUICELLULARTOGGLE_GLOBAL_H
